# Generated by Django 4.2.9 on 2024-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название новости')),
                ('autor', models.CharField(default='Anon', max_length=30, verbose_name='Автор')),
                ('time', models.TextField(verbose_name='Время публикации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.TextField(verbose_name='Ссылка на статью')),
                ('source', models.TextField(verbose_name='Источник новости')),
                ('count_comments', models.TextField(verbose_name='Количество комментариев')),
                ('news_id', models.TextField(verbose_name='ID новости на исходном сайте')),
                ('score', models.TextField(verbose_name='Рейтинг новости но исходном сайте')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['time'],
            },
        ),
    ]
